# Run ape test on Github CI
name: Automated test suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-python:

    runs-on: ubuntu-latest

    # Only run the action for the latest push
    # See https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'poetry'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install Ape and dependencies
        run: |
          poetry env use '3.12'
          poetry install --all-extras
      - name: Install Ape plugins
        run: |
          poetry run ape plugins install .
      - name: Compile smart contract dependency packages
        run: |
          poetry run ape pm compile
      - name: Compile our smart contracts
        run: |
          poetry run ape compile
      - name: Run test scripts
        run: |
          poetry run pytest 
 
